version: '3.8'

services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - "8181:8181"
    volumes:
      - ./memu/policy/rules:/rules
    command:
      - "run"
      - "--server"
      - "--watch"
      - "/rules"
